Questo modulo contiene la mia configurazione della tastiera e lo script aggiuntivo necessario per configurarla su Windows 10.

La tastiera e' una tastiera fisica TKL UK ISO, ma con i tasti US, impostata su Windows 10 col layout =US intranational layout=.  Questo viene poi modificato, mediante uno script AHK, per aggiungervi tutte le lettere accentate italiane (maiuscole e minuscole) ed disabilitare i /dead keys/, ripristinando per i tasti dei segni diacritici il loro comportamento ordinario.

Tutto cio' e' necessario in Windows, non essendovi un layout simile a disposizione; su Linux viceversa e' possibile ottenere un comportamento quasi identico, semplicemente inpostando il layout come =Tastiera IT, con tasti US e accentate= 

** procedura di configurazione

Procurarsi una tastiera TKL UK ISO Layout con i tasti (/keycap/) agguntivi US (p.es. Keychron K8).

Sostituire i tasti dell'UK layout con i corrispondeti tasti US, fino ad ottenere una disposizione simile alla tastiera US ISO. Piu' precisamente si deve sostituire o commutare sei tasti: tre in R1, nessuno in R2, due in R3, uno in R1. 
Partendo dall'UK ISO Layout descritto qui (), bisogna operare sui tasti evidenziati in blu, fino a raggiungere la disposizione di una tastiera US ISO). Questo produrra' una configurazione di tasti non alfabetici "di tipo US", con il tasto =\ |= duplicato (accanto allo shift di sinistra e accanto al tasto Enter, in basso).

Configurare nel sistema operativo la tastiera come "US International layout", per poter avere attivo il tasto AltGr come tasto separato;

Scaricare dal sito AHK (https://www.autohotkey.com) il tool in versione /portable/, scegliendo cioe' il file .zip che non richiede installazione (https://www.autohotkey.com/download/ahk.zip), e decomprimerlo in una directory.

Scaricare lo script trovamiunnome.ahk da questo repository e salvarlo nella stessa directory del tool o dove si vuole.

Associare l'estensione .ahk al lancio della versione UTF 64 del tool (=XXXXXXXX.EXE=).

lanciare lo script .ahk ed eventualmente aggiungerlo alla esecuzione automatica, all'avvio di Windows.

Se tutto e' stato eseguito correttamente comparira' il logo verde "H" nella barra di stato e la tastiera sara' configurata come desiderato.

** riferimenti

http://www.farah.cl/Keyboardery/A-Visual-Comparison-of-Different-National-Layouts/
